services:
  ubuntu:
    # 1. Instruye a Docker Compose a construir la imagen
    #    usando el Dockerfile que está en la carpeta actual (.).
    build:
      context: .
      dockerfile: Dockerfile

    # 2. Asigna un nombre específico al contenedor, para fácil acceso (opcional).
    container_name: sap-dev

    ports:
      - "3003:3000"

    volumes:
      - ./scripts:/scripts
      - /scripts/node_modules